### ISSUE TITLE
Incompatibility between MailChimp and PaidMembershipsPro

### ISSUE THREAD

**Issue by BigPhilOV** [strangerstudios/pmpro-address-for-free-levels#1]
Wordpress by default asks for Username and email. 
Most people who use MailChimp require a First Name field for campaigns.
The PaidMembershipsPro setup does not seem to recognise the wordpress Username field or have the ability to require the First Name field to be completed.
Any thoughts on how to get proper integration with MailChimp working?
Cheers, Phil

**Comment by strangerstudios** [comment]
Pretty sure we are syncing names well now with PMPro MailChimp. Check it out over here and open an issue there if it's not working https://github.com/strangerstudios/pmpro-mailchimp
