### ISSUE TITLE
User fields not appearing in user profile

### ISSUE THREAD

**Issue by karelmartens** [strangerstudios/pmpro-address-for-free-levels#2]
Hi,

Could you please add these fields to the user profile as it's impossible to edit the info once entered otherwise.

**Comment by PiotrKrzyzek** [comment]
I'm also looking for a solution to this one.

**Comment by strangerstudios** [comment]
You can use our Register Helper plugin
http://www.paidmembershipspro.com/add-ons/free-add-ons/pmpro-register-helper-add-checkout-and-profile-fields/

and then this code gist to add the billing address fields (added via this plugin or core PMPro) to the profile page:
https://gist.github.com/strangerstudios/7771903
