### ISSUE TITLE
Conflict with International Addresses

### ISSUE THREAD

**Issue by ThomasLeCoz** [strangerstudios/pmpro-address-for-free-levels#4]
Hey guys,

Just found a bug: when you have this plugin (address for free levels) coupled with pmproia and you try to remove required fields, this plugin overrides your unset() instructions for the filter.

Probably because you group everything in the filter pmpro_required_user_fields whereas Int. Addresses. uses pmpro_required_billing_fields.

Fixed it in the code by removing the line of the field I didn't want required, but I'm sure there's a more elegant way to do so ;)

**Comment by strangerstudios** [comment]
I believe this is fixed with the latest versions of all plugins. Please open again if you are still having this issue.
